---
deployment:
  tasks:
    - export DEPLOYPATH=/home/techtone/cb.unistudents.gr/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH